### ISSUE TITLE
请问刷一个礼物会推送两条礼物信息，怎么解决

### ISSUE THREAD

**Issue by ningbinChen** [skmcj/dycast#12]

**Comment by LPQingFeiDeYi** [comment]
同问

**Comment by LPQingFeiDeYi** [comment]
有些礼物会推送两条，有些不会

**Comment by skmcj** [comment]
推送消息是对dy的wss进行的解析转发，如果真的有同一消息推送多次，那应该也是wss推送了两次。
要解决这种问题，只能在程序内加个消息过滤，每条消息都有个ID，自己判断过滤一下

**Comment by ningbinChen** [comment]
> 推送消息是对dy的wss进行的解析转发，如果真的有同一消息推送多次，那应该也是wss推送了两次。 要解决这种问题，只能在程序内加个消息过滤，每条消息都有个ID，自己判断过滤一下

但是他们的ID也是不同的，没有区别规律。我现在是通过时间判断（若4秒内同样的礼物出现我会过滤掉，这解决不了根本问题但是

**Comment by skmcj** [comment]
你是如何发现同一礼物推送两条的，有没有复现的房间号或对应的信息截图

**Comment by ningbinChen** [comment]
其实您可以自己跑一下代码试一下，立马就可以复现出来

**Comment by skmcj** [comment]
大概修复了，为礼物消息增加了一个repeatEnd属性，当其大于零时表示重复(个人猜测)，可自行测试判断下是否正确

**Comment by LPQingFeiDeYi** [comment]
好像是可以，测试了下，repeatEnd判断，大于0的表示是重复的，大于0的过滤就行了
