### ISSUE TITLE
完美实现纯协议

### ISSUE THREAD

**Issue by Mrqjj** [skmcj/dycast#14]
![output](https://github.com/skmcj/dycast/assets/29968140/b5cfa2ad-eb42-4078-84ad-0c24997743fb)

**Comment by skmcj** [comment]
👍👍🏻👍🏿

**Comment by Mrqjj** [comment]
您好，您发的邮件我已经收到；在空闲时间我会给您回复的。

**Comment by Mrqjj** [comment]
您好，您发的邮件我已经收到；在空闲时间我会给您回复的。
