### ISSUE TITLE
作者可以加个发送信息的功能吗？

### ISSUE THREAD

**Issue by ysben** [skmcj/dycast#3]

**Comment by skmcj** [comment]
可以详细点描述你的想法，如发送什么信息？以什么方式发送？如有必要后期有空会考虑添加

**Comment by ysben** [comment]
就是在直播间模拟发送聊天信息这个功能！

**Comment by skmcj** [comment]
如果你是需要在直播间发弹幕消息，那可自行前往目标直播间直接发就行，因为那涉及到平台账户的登录

**Comment by ysben** [comment]
我想用脚本来自动发信息，不知道作者有没有好的建议呢？

**Comment by skmcj** [comment]
你可以去研究解析下平台发消息的接口
