### ISSUE TITLE
感谢作者开源, 我有一个关于打包的问题

### ISSUE THREAD

**Issue by Hujiazeng** [skmcj/dycast#4]
npm run build打包后打开index.html提示CORS报错, 继而安装了http-server开启了服务,  网页可以正常打开,  但是连接不上房间, 报错是"GET /dy/xxxxx(房间号)" Error (404): "Not found"

我想问一下打包用上面的方法对吗, 应该怎么打包才可以正常使用(能打包成exe文件就更好)

**Comment by skmcj** [comment]
打包命令没错，CORS报错是由于项目中有一接口跨域了，打包出来部署需在服务端自行处理跨域，将'/dy/'映射到'https://live.douyin.com/'
