### ISSUE TITLE
python翻译

### ISSUE THREAD

**Issue by Jasper20155** [skmcj/dycast#6]
您好，请问signature参数您那边是如何解析的，我这边想用python翻译一下，结果报错说这个函数没有
<img width="1463" alt="图片" src="https://github.com/skmcj/dycast/assets/106738381/9f16951b-544b-41ad-87ba-7ae4dc0803b6">
所以想问一下，我只引入了signature.js，请问另外两个也是必须的吗 model.js和webmssdk.js

**Comment by skmcj** [comment]
frontSign是webmssdk里定义的
