### ISSUE TITLE
好像现在用不了了

### ISSUE THREAD

**Issue by kilnonedre** [skmcj/dycast#8]

**Comment by skmcj** [comment]
刚push了，应该可以了

**Comment by kilnonedre** [comment]
> 刚推了，应该可以了

还是不行
![image](https://github.com/skmcj/dycast/assets/90387303/a39ede77-cff3-43dd-b1be-7ef3456d28fb)
卡在这个转json了

**Comment by kilnonedre** [comment]
> 刚push了，应该可以了

而且好像获取websocket的二进制转码也有问题，当然也有可能是我写入死数据导致的

**Comment by skmcj** [comment]
我部署的没有问题呀，一切正常
![image](https://github.com/skmcj/dycast/assets/71473194/3970effc-3bd8-47d4-a1b2-5e2708ec475c)

**Comment by user-zd** [comment]
const REGLIST = [
        {
          reg: /\\{1,7}"/g,
          str: '"'
        },
        {
          reg: /"\{/g,
          str: '{'
        },
        {
          reg: /}"/g,
          str: '}'
        },
          {
              reg: /"\[/g,
              str: '['
          },
          {
              reg: /]"/g,
              str: ']'
          }
      ];

**Comment by user-zd** [comment]
`const REGLIST = [
        {
          reg: /\\{1,7}"/g,
          str: '"'
        },
        {
          reg: /"\{/g,
          str: '{'
        },
        {
          reg: /}"/g,
          str: '}'
        },
          {
              reg: /"\[/g,
              str: '['
          },
          {
              reg: /]"/g,
              str: ']'
          }
      ];`
![image](https://github.com/skmcj/dycast/assets/34637451/fc63c8b3-d4bf-4b11-bd60-b35a9be12e47)

**Comment by user-zd** [comment]
@kilnonedre 修改REGLIST即可

**Comment by user-zd** [comment]
@skmcj 改一下REGLIST 我已经贴在上面了

**Comment by kilnonedre** [comment]
> 刚push了，应该可以了

![image](https://github.com/skmcj/dycast/assets/90387303/086b784b-f945-42d3-a8a5-2206ccb90792)
w's'm为什么我构建完之后，再去访问抖音，就变成这样了

**Comment by user-zd** [comment]
@kilnonedre 你这是去请求页面没拿回页面吧，加个heasers

**Comment by kilnonedre** [comment]
> hea

**Comment by kilnonedre** [comment]
> @kilnonedre 你这是去请求页面没拿回页面吧，加个heasers

怎么加啊，我这个是访问通了

**Comment by user-zd** [comment]
![image](https://github.com/skmcj/dycast/assets/34637451/4a484f4d-c1c7-4e50-8450-dcf6a49fe951)
![image](https://github.com/skmcj/dycast/assets/34637451/c65ce911-f40f-4675-ae16-ff2d822430a6)
我这边正常

**Comment by kilnonedre** [comment]
> ![image](https://user-images.githubusercontent.com/34637451/266560823-4a484f4d-c1c7-4e50-8450-dcf6a49fe951.png) ![image](https://user-images.githubusercontent.com/34637451/266560873-c65ce911-f40f-4675-ae16-ff2d822430a6.png) 我这边正常

也就是说后端也需要进行配置是吧

**Comment by user-zd** [comment]
他的前端代码是加了代理的

**Comment by user-zd** [comment]
看你需求，我是转化为接口了

**Comment by kilnonedre** [comment]
> 看你需求，我是转化为接口了

大佬，他又出现了部分视频无法转化json的问题
